### ISSUE TITLE
Fatal error in your paper

### ISSUE THREAD

**Issue by jiajinuiuc** [IssamLaradji/M-ADDA#7]
You are solving **unsupervised** domain adaptation, however, I find out **you use target label** in your training procedure.
That is cheating ！！

**Comment by IssamLaradji** [comment]
which line?

**Comment by jiajinuiuc** [comment]
This line: loss_tgt = criterion(pred_tgt, label_tgt) in 'M-ADDA/train.py'
Since you paper is named '**Unsupervised Domain Adaptation**', you are not allowed to use target domain labels when training your target encoder.

**Comment by IssamLaradji** [comment]
Ah look carefully. I haven't used the target labels.

`label_tgt` is just the discriminator label which is all `ones` for training the encoder or all `zeros` for training the discriminator.

**Comment by jiajinuiuc** [comment]
Sorry, this line:  fit_center( src_model, tgt_model, src_trainloader, tgt_trainloader, tgt_opt, epochs=1)
And in your paper: 
![image](https://user-images.githubusercontent.com/26575424/95592347-7d23f980-0a16-11eb-9c27-054719048007.png)
You are using target label to regularize your embedded target feature distribution.
Please correct me if I am wrong.

**Comment by IssamLaradji** [comment]
That's a typo yah. In Equation 4, you will see that the labels are not used, and in the code https://github.com/IssamLaradji/M-ADDA/blob/master/losses.py#L27-L57, the labels are not used as well.

**Comment by IssamLaradji** [comment]
I am closing the issue as there is no cheating and the paper is doing proper **unsupervised domain adaptation**.
